### PR TITLE
✨ Add structured meta data

### PR DESCRIPTION
**Pull request by robinvanopstal**
Add `METADATA.yaml` to working group repository in order to provide the following data for #1699 in a structured way:
- Group Name 
- Short Description
- Facilitator
- Members
- Communication Channels

/cc @pbakaus

### CODE REVIEW

**Comment by twifkak** [comment]
Thanks, Robin; sorry for the delay. Can you provide context on this? #1699 in what repo?

**Comment by twifkak** [comment]
@googlebot

**Comment by matthiasrohmer** [comment]
Hi Devin! Huh, strange. Sometimes mentioning issues numbers without a specific repository works, sometimes not. It's ampproject/amp.dev#1699. We've started adding META.yamls to every working group repository to have their information easily importable from a central location for amp.dev. Feel free to reach out if you need more information 🙂

**Comment by twifkak** [comment]
Thanks for the context! Sorry for the delay; will approve and merge now.

**Pull request merged**
